### PR TITLE
Fixing The Withdraw Flow

### PR DESCRIPTION
**Pull request by AtelyPham**
Check out from https://github.com/webb-tools/webb-dapp/pull/806

## Summary of changes
- Add logging service by @AhmedKorim 
- Refactoring redundant / duplicated deposit/transfer/withdraw codes from dApp
- Update the relayer for consuming new API
- Got the deposit (same-chain and cross-chain) working 
- Got the withdrawal (same-chain and cross-chain) working with or without relayer
- In the withdraw flow, display the switch chain button when the balance on the active chain is 0. Otherwise
  - Auto switch to an available chain that has a balance greater than 0 and if the user only has one available chain
  - Or display a list of available chains to switch into to withdraw
- In the deposit flow, auto-switch to the wrapping function if a user does not have a balance
- Display the user's balance on the withdrawal flow
- Change the delay of the amount tooltip in the withdrawal flow

### Reference issue to close (if applicable)
- Related https://github.com/webb-tools/webb-dapp/issues/841
- Closes https://github.com/webb-tools/webb-dapp/issues/835
- Related https://github.com/webb-tools/webb-dapp/issues/840
- Related https://github.com/webb-tools/webb-dapp/issues/838
- Closes https://github.com/webb-tools/webb-dapp/issues/794
- Closes https://github.com/webb-tools/webb-dapp/issues/817
- Related https://github.com/webb-tools/webb-dapp/issues/797

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### Demo

https://www.loom.com/share/2bc0f71b7ef040a285425d85c9e7fdc4

### CODE REVIEW

**Review by salman01zp — APPROVED** [review]
withdrawal flow looks good. Great work @AtelyPham

**Comment by AtelyPham** [comment]
Adding changes:

- In the withdraw flow, display the switch chain button when the balance on the active chain is 0. Otherwise
  - Auto switch to an available chain that has a balance greater than 0 and if the user only has one available chain
  - Or display a list of available chains to switch into to withdraw
- In the deposit flow, auto-switch to the wrapping function if a user does not have a balance
- Display the user's balance on the withdrawal flow
- Change the delay of the amount tooltip in the withdrawal flow
- 

Linked issues:

- Related https://github.com/webb-tools/webb-dapp/issues/841
- Closes https://github.com/webb-tools/webb-dapp/issues/835
- Related https://github.com/webb-tools/webb-dapp/issues/840
- Related https://github.com/webb-tools/webb-dapp/issues/838
- Closes https://github.com/webb-tools/webb-dapp/issues/794
- Closes https://github.com/webb-tools/webb-dapp/issues/817
- Related https://github.com/webb-tools/webb-dapp/issues/797

**Comment by dutterbutter** [comment]
@AtelyPham great work as usual! A couple things I noticed to be addressed. 

1. Update container header to read "Wrap and Deposit Completed" once the transaction is successful or if it fails indicate "Wrap and Deposit Failed". 
2. The user currently needs to select the copied note checkbox in order to enable "New Transaction" button, this shouldn't be the case as the user would have already made that selection when initiating the deposit. 
3. Update the transaction card header to read "Transaction Completed" instead of "Transaction Processing" once the tx is completed successfully, the inverse would be "Transaction Failed" when it has been unsuccessful.   
4. Lastly, **and this could be done in a subsequent PR** the transaction card remains present until the user selects the "Dismiss" button. We should update this to disappear upon the users next operation (e.g. clicks "New Transaction") or disappear after X amount of time. 

**See below screenshot.** 

CleanShot 2023-01-09 at 06 16 28

**Review by dutterbutter — CHANGES_REQUESTED** [review]
See above comment for requested changes.

**Comment by devpavan04** [comment]
Transaction Processing Component @monaiuu @AtelyPham @dutterbutter 
https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1?node-id=1200:22610#339222045

**Comment by dutterbutter** [comment]
On Withdrawal page: 

CleanShot 2023-01-09 at 07 40 35

**Comment by drewstone** [comment]
Deposit flow review: https://www.loom.com/share/84852dc4da514957847fbc912886608a

**Comment by drewstone** [comment]
Chain switching issues: https://www.loom.com/share/84852dc4da514957847fbc912886608a

**Comment by AtelyPham** [comment]
Resolved the display comments @dutterbutter. I'm working on "Auto switching to wrapping function when a user has no balance" on the deposit flow. Little stuck with state and side effect, I'll continue to investigate

**Comment by AtelyPham** [comment]
We have "Auto switching to wrapping function when a user has no balance" on the deposit flow.

**Pull request merged**
