### PR TITLE
Sets up crowdloan page and input

### LINKED ISSUE #420: [SPEC] Crowdloan integration into dApp
## Overview

This issue outlines a potential approach to integrate the crowdloan into the dApp, and follow issue #419. 

## Tasks

- [ ] Create `Crowdloan<T>` interface in `react-environment/src/webb-context/` and add to `WebbMethods<T>`
- [ ] Add `PolkadotCrowdloan` to the `webb-polkadot-provider` , empty and disabled for `webb-web3-provider`

```
export abstract class Crowdloan<T> extends EventBus<CrowdloanEvents> {

	constructor(protected inner: T) {}

	async getBalance(){}

	async getContributions() {}

	async contribute(amount: number) {}
}
```

```
export class PolkadotCrowdloan implements CrowdLoan<WebbPolkadot> {

	const PARA_ID = XXX;

	async getBalance() {
		this.inner.api.query.crowdloan.funds(PARA_ID)
		// then parse for total balance
	}

	async getContributions() {
		this.inner.api.derive.crowdloan.contributions()
	}

	async contribute(amount: number) {
		this.inner.txBuilder.build(
			{
				section: 'crowdloan',
				method: 'contribute',
			}
			{
				PARA_ID,
				amount,
			}
		);
	}
}
 ```
 
 #### Missing inputs

- We currently do not have a secured long term parachain id (`PARA_ID`)

### Testing

- [ ] Test crowdloan using Rococo / Westend

### PR DESCRIPTION
**Pull request by drewstone**
This sets up a basic crowdloan input page and contributes the provided input to a hardcoded parachain ID. We just need to:
- Update the UI with the proper design @dutterbutter @AtelyPham 
- Add copy to the content for what the crowdloan is for.

Closes #420 and related to #419

### CODE REVIEW

**Comment by dutterbutter** [comment]
Some remaining logic related work needed: @drewstone 

- [ ] Need to check the users deposit amount against crowdloan cap 
- [ ] Need to validate that the user's deposit is greater than 0.1 KSM
- [ ] Need to calculate a rough estimate of users rewards see #419 for calculation  
- [ ] Need to be able to fetch total contributed amount and number of contributions into the crowdloan 
- [ ] When a user selects crowdloan tab it should auto change to polkdot.js wallet 
- [ ] If the user does not have polkadot.js wallet installed we should point them to install the extension

**Review by AhmedKorim — APPROVED** [review]
LGTM

**Review by dutterbutter — CHANGES_REQUESTED** [review]
Please finalize the requested logic additions.

**Comment by drewstone** [comment]
@dutterbutter would be good to coordinate design implementation. This is what it currently looks like:

image

**Comment by drewstone** [comment]
@AtelyPham this is the PR to work on for updating the crowdloan page UI.

**Comment by dutterbutter** [comment]
@drewstone I want to confirm the data points mentioned. Regarding the calculation of user rewards, I think it should follow this:

`(your_contribution_to_crowdloan / total_contribution) * alloted_rewards_pool`

So if Jon contributed **10 KSM** 
and the total amount raised is **100,000 KSM** 
and the reward pool cap is set at **200,000 KSM** then...

```
(10 / 100,000) * 200,000 = 20 
Jon's estimated rewards would be 20 at a 1:2 ratio. 
```

This assumes the data field 'Raised' that is mentioned in this PR refers to the amount contributed. Can you confirm if this accurate?

**Pull request closed without merging**
