### PR TITLE
Fixes hubble bridge layout issues

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Fixes hubble bridge layout issues.

### Proposed area of change

- [x] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Screen Recording

**Previous:**

https://github.com/webb-tools/webb-dapp/assets/53374218/708b3ed4-6ab0-43b4-b13b-0e6a54037a54

**Current:**

https://github.com/webb-tools/webb-dapp/assets/53374218/a6436f06-e769-4c13-892a-731cc9b3839e

### CODE REVIEW

**Comment by monaiuu** [comment]
When addressing layout issues, lets ensure we double check all dimensions first. Currently, the video shown is in `1440px` and when it scales to other dimensions the layout is inconsistent. 

Screenshot 2023-10-04 at 10 12 31 AM
Screenshot 2023-10-04 at 10 10 11 AM
Screenshot 2023-10-04 at 10 10 03 AM
Screenshot 2023-10-04 at 10 10 20 AM

**Review by monaiuu — CHANGES_REQUESTED** [review]
When addressing layout issues, lets ensure we double check all dimensions first. Currently, the video shown is in `1440px` and when it scales to other dimensions the layout is inconsistent. 

Screenshot 2023-10-04 at 10 12 31 AM
Screenshot 2023-10-04 at 10 10 11 AM
Screenshot 2023-10-04 at 10 10 03 AM
Screenshot 2023-10-04 at 10 10 20 AM

**Comment by devpavan04** [comment]
@monaiuu, I apologize for the oversight. I didn't observe this issue while running the dapp locally. The same issue persists, as I can now see the bug in the deployment preview, but not in the local run. I'll address and resolve this asap.

Deployment Preview:

CleanShot 2023-10-04 at 10 20 08

Running locally:

CleanShot 2023-10-04 at 10 20 20

**Review by drewstone — APPROVED** [review]

**Comment by devpavan04** [comment]
@monaiuu Issue was with `note account`. Could see the bug only when `note account` was not created yet. Layout is fixed now, please check. Thanks @AtelyPham for helping me to reproduce this issue ! :)


https://github.com/webb-tools/webb-dapp/assets/53374218/47daf087-b8e0-4129-a962-edfe1b2a7151

**Review by monaiuu — APPROVED** [review]

**Pull request merged**
