### PR TITLE
Setup Animations for Sections on the Marketing Page

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes

- Add dotlottie player to support optimal dotlottie file type.
- Animations on the "Futures of Privacy is Connected" section
	- Proof of Ownership animation
	- Proof of Identity animation
	- Privacy ecosystems animation
- Animations on the "Privacy Scales" section
	- Swiper content with Interactive pagination and prev/next buttons
	- Illustrations with transitions
- Adding a new Satoshi font family for the marketing page
- Animated background for hero section

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/webb-dapp/issues/810
- Closes https://github.com/webb-tools/webb-dapp/issues/811

### Additional info

The hero background will be improved iteratively with the chain icons and gradient background. Thanks, @seeddisperser for helping me with the animations 🙏 .

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### Screenshot

https://user-images.githubusercontent.com/60747384/209225371-eccf189b-6a2c-4050-853f-db8f4cea0800.mp4

### CODE REVIEW

**Comment by dutterbutter** [comment]
@AtelyPham it doesn't seem the deployment picked up on the animations. I will investigate if its caused by deploying the site as a static site and report back.

**Comment by dutterbutter** [comment]
Yeah it seems `.lottie` files from `/animations/` directory are not being picked up during deployment.

**Comment by dutterbutter** [comment]
🔥🔥🔥 nice job @AtelyPham

**Comment by drewstone** [comment]
Great work @seeddisperser @AtelyPham, I think the transitions on some of the infographs are a bit fast and should only begin once they come into view.. I've noticed by the time I scroll down that they are already on the 2nd or 3rd slide.

**Comment by AtelyPham** [comment]
Added gradient background for hero section and fixed the swiper autoplay issue (only play when the view is focused).

**Comment by drewstone** [comment]
This is what I see in the development preview @AtelyPham 
image

**Comment by drewstone** [comment]
This image seems grainy and not great CC @seeddisperser @monaiuu 
image

**Comment by drewstone** [comment]
These are out of place
image

**Comment by drewstone** [comment]
Can you make this just "Copyright (C) 2022" or remove what doesn't make sense here
image

**Review by drewstone — CHANGES_REQUESTED** [review]
Left changes above

**Comment by seeddisperser** [comment]
Awesome—so cool to see the animations live!

A few things I notice:

1. make sure to include the updates to the landing. Some of the gradient sections now have a dark background, and the footer has been improved. 
2. When the "how the future of privacy scales" slides change, the illustration should transition from `opacity: 0` to `opacity: 1` so that it appears to fade in. 
3. the hero illustration is scaled larger than in the mockups.
4. I see a bunch of small errors with the illustrations. Will go through an reexport the files + will loop the hero
5. careful to preserve the ratios of the image sizes. I see that the illustration on the "Zero-Knowledge Cross-Chain Bridging" is horizontally stretched. Similarly some of the images appear to have a width based on `vw`, or some horizontal ratio, since they change width when the window size changes. My preference for images that have to scale horizontally is that they are anchored to the left, with their parent element set to `overflow: hidden`.
6. The tabs such as the "proof of ownership" and "proof of identity" are missing hover states
7. it looks like mobile styling hasn't been started yet. I would recommend starting on this soon, since I suspect there will be challenges, questions about scaling, and some back and forth about getting the correct break points.  Excited to see how it looks on a mobile screen.

**Comment by AtelyPham** [comment]
Fixed:

- Mis-aligned text on hero on widescreen
- Out-of-place gradients
- Copyright text on the footer
- Update "Privacy Scale" and "Footer" to match the new design

**Review by drewstone — APPROVED** [review]

**Comment by seeddisperser** [comment]
@AtelyPham Updated animations are here:
Hero: [loop](https://app.lottiefiles.com/share/f7092cc2-54c2-4a41-94bb-61347ccefa26) variation, and [non-loop](https://app.lottiefiles.com/share/75161a17-2c10-42e8-b5aa-7c0d28f0a749) variation

[shielded pool](https://app.lottiefiles.com/share/5df59dd8-561c-45a8-8a8f-8e03c8fbed6e)
[shielded identity](https://app.lottiefiles.com/share/7115615f-cf5c-4fcf-8da1-72cdcf9bc222)
[ecosystem](https://app.lottiefiles.com/share/daf53621-724b-434b-8111-a2468f18a8d5)

**Comment by seeddisperser** [comment]
And some edits

1. The tangle network card should be updated
Screenshot 2023-01-04 at 12 04 57 AM
2. the columns and gap need to be the same across rows.
Screenshot 2023-01-04 at 12 11 25 AM
3. The merkle tree illustrations were updated so that the lines are lighter. Assets are [here](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1028%3A32475&t=haYBbVwmq7hjtVT6-1). 
Screenshot 2023-01-04 at 12 07 25 AM
4. The images are low resolution. When exporting the images from figma, make sure to select 2x the resolution.
Screenshot 2023-01-04 at 12 09 07 AM

Will have a few more edits tomorrow

**Pull request merged**
