### PR TITLE
Add more favicons for different browser sizes

### LINKED ISSUE #1644: [TASK] Update DKG stats favicon
### Overview

Currently the DKG stats-dapp favicon is smaller compared to the favicon used in https://www.tangle.tools/. We need to match the size of favicons across all the tangle applications.

CleanShot 2023-09-21 at 04 44 00

### PR DESCRIPTION
**Pull request by drewstone**
## Summary of changes
_Provide a detailed description of proposed changes._
- Adds a lot of favicons

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [x] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
- Closes #1644

### CODE REVIEW

**Comment by AtelyPham** [comment]
The sizes of the favicons on Tangle Marketing and Tangle Stats are still different.

image

**Review by AtelyPham — COMMENTED** [review]
The sizes of the favicons on Tangle Marketing and Tangle Stats are still different.

image

**Comment by drewstone** [comment]
I’m aware, I think it won’t get larger and we should close this task.

**Comment by drewstone** [comment]
Ya I'm aware this didn't change it, we'd have to either get a bigger favicon or just not worry about this. CC @monaiuu maybe 16x16 isn't enough and we need 32x32, can you provide?

**Comment by monaiuu** [comment]
> Ya I'm aware this didn't change it, we'd have to either get a bigger favicon or just not worry about this. CC @monaiuu maybe 16x16 isn't enough and we need 32x32, can you provide?

It is because the margins are inconsistent using different images, device specification and favicon sizes should not matter. The correct favicon file can be accessed here: https://www.notion.so/hicommonwealth/Tangle-Logo-029bec068f1a4690a7defc92125be03d?pvs=4

We should remove all old favicon files for Tangle, and opt for the above image in Notion instead.

**Pull request closed without merging**
