### PR TITLE
Update copy to remove recent tx details

### PR DESCRIPTION
**Pull request by monaiuu**
## Summary of changes

- Proposing to update copy to introduce Tangle dApp on Account Dashboard, as recent tx is no longer going to be implemented. 

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes

### Screenshot
Screenshot 2024-04-04 at 12 40 26 PM

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by yurixander — APPROVED** [review]

**Review by drewstone — APPROVED** [review]

**Comment by drewstone** [comment]
Need to run `yarn lint` or `yarn format` @monaiuu, LG otherwise!

**Comment by drewstone** [comment]
@monaiuu @yurixander @vutuanlinh2k2 wait why don't we just remove this?

**Comment by yurixander** [comment]
> @monaiuu @yurixander @vutuanlinh2k2 wait why don't we just remove this?

We could, but would need to replace it with something to take its place in the layout, otherwise a big gap would be left behind. If we just expand the account summary card that may look strange as well

**Comment by drewstone** [comment]
Big gap is OK

**Comment by monaiuu** [comment]
I think big gap looks odd and makes the application feels incomplete. It also makes the interface seem off-balance and asymmetric. This is the landing page of Tangle dApp, so I think instead of removing the container altogether, we could just use the space to introduce Tangle dApp. 

Screenshot 2024-04-02 at 10 10 09 AM

**Pull request merged**
