### PR TITLE
Fix bridge mobile view

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes

- Removed breadcrumbs in mobile view.
- Removed banner in mobile view.
- Fixes layout/padding & margins in mobile view.

### Proposed area of change

- [x] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes https://github.com/webb-tools/webb-experiences/issues/206

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/53374218/539a546d-ccb6-471c-bb29-3b45dea45e55

### CODE REVIEW

**Comment by monaiuu** [comment]
Unable to preview the deployment link image

Can we attempt to resolve this deployment failure issue as it has been a perpetual problem for the last while?

**Comment by AtelyPham** [comment]
The CI is failing @devpavan04.

**Comment by monaiuu** [comment]
Can we increase the size of these numbers? Inconsistent display between number in fixed and custom amount. Lets increase custom ones the same size as fixed display.

**Comment by devpavan04** [comment]
Updated header `Connect Wallet` button.

https://github.com/webb-tools/webb-dapp/assets/53374218/b3f84713-e2e6-4dc2-ac98-2f8cc705efee

**Review by monaiuu — APPROVED** [review]

**Pull request merged**
