### PR TITLE
fix: fix UI break on Governance System section

### LINKED ISSUE #1357: [UI] Fix the Governance Section for the Tangle website when resizing
**Is your UI update related to a problem? Please describe.**
When resizing the screenlet from desktop to tab, the Governance System section has a break 

**Describe the solution you'd like (include image or link to prototype)**
The UI should still align properly when resizing

**Additional context**

Screenshot 2023-06-21 at 17 56 12

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes
Fix the Governance Section for the Tangle website when resizing

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [x] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #1357 

### Screen Recording
_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/11c48fe3-bee9-4a70-942f-46b4c3699b46

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by drewstone** [comment]
This still looks quite awkward, @monaiuu can we design this more thoughtfully?

**Comment by vutuanlinh2k2** [comment]
@monaiuu we can create a new task later on if you have to prioritize other tasks right now. If you are ok with that we can merge this right away.

**Comment by monaiuu** [comment]
> This still looks quite awkward, @monaiuu can we design this more thoughtfully?

@drewstone Can you provide more details or screenshots on where you think it looks awkward so I can address it appropriately. 

(One thing I would also like to address too is the cropping of the image on the right when going into large views.)

@vutuanlinh2k2 sure that sounds good, I can create a separate issue to address this section altogether.

**Comment by monaiuu** [comment]
I can address this quickly. Let me get back to you in the next hour.

**Review by monaiuu — COMMENTED** [review]
Perhaps the issue as to why this section looks a bit awkward when viewed at smaller breakpoints is due to the image taking up too much space at the top. Let's try placing the image at the bottom instead and see if that improves the overall view.

Screenshot 2023-06-22 at 8 01 48 PM

Figma file updated for reference:
https://www.figma.com/file/jrtQ1Gvvb1kJdt7HXAkUX4/%F0%9F%AA%A2-Tangle-Website?type=design&node-id=2326%3A282031&mode=design&t=8abCNiXRkpez5D6C-1

**Comment by drewstone** [comment]
We'll merge and continue to improve. This didn't get handled as soon as I would have hoped @monaiuu . I would've liked to have you make the decision and have gotten it updated with 1 day's time. Let's discuss soon what happened here.

**Pull request merged**
