### PR TITLE
Fix signin message

### PR DESCRIPTION
**Pull request by drewstone**
## Summary of changes
_Provide a detailed description of proposed changes._
- Updates the sign in message to be richer in detail. Still needs updates pending how we will switch different domain/origins.

### Proposed area of change
_Put an `x` in the boxes that apply._

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes 

### Screen Recording
_If possible provide a screen recording of proposed change._
image

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by AtelyPham — COMMENTED** [review]
For the `domain/origins`, we can move its values into the environment variables (fallback to `localhost`, so that we can set the values base on the environments).

**Comment by dutterbutter** [comment]
The links check failing here is resolved in #1003 so no need to address here.

**Review by AtelyPham — APPROVED** [review]
Extracted the domain to the environment variable and fallback to localhost. Please help me to review the GA actions files changes @dutterbutter.

**Comment by dutterbutter** [comment]
@AtelyPham to confirm the value of `NX_BRIDGE_APP_DOMAIN` is simply `app.webb.tools` ?

**Pull request merged**
