### PR TITLE
Faucet Login and Mint Tokens Integration

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
_Provide a detailed description of proposed changes._
- Integrate the Twitter Login flow
- Integrate the Mint Tokens flow
- Improve error handling (integrate [`neverthrown`](https://www.npmjs.com/package/neverthrow) usage)

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [x] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes `NaN`

### CODE REVIEW

**Comment by AtelyPham** [comment]
```
NEXT_PUBLIC_APP_URL="http://localhost:4200" # optional
NEXT_PUBLIC_FAUCET_BACKEND_URL="http://127.0.0.1:8000" # optional
NEXT_PUBLIC_TWITTER_CLIENT_ID="<YOUR_TWITTER_CLIENT_ID>"
TWITTER_CLIENT_SECRET="<YOUR_TWITTER_CLIENT_SECRET>"
```

We need to set these environment variables in the Github Secret @dutterbutter.

**Comment by dutterbutter** [comment]
Please resolve conflicts @AtelyPham

**Comment by dutterbutter** [comment]
I cannot seem to login via Twitter even though logging in produces a successful response on the local server. 

**After logging in via Twitter:**
CleanShot 2023-04-11 at 08 37 03

**Server success:**
CleanShot 2023-04-11 at 08 37 13

**Comment by dutterbutter** [comment]
@AtelyPham can we add a "Add token to MetaMask" button so its readily easy for users to see the tokens present in their wallet.

**Comment by AtelyPham** [comment]
Yes, we can definitely do that! However, the data we currently have is mocked, including the claim data on the backend. Nonetheless, I’ll work collaboratively with Shady to get the actual data for the faucet.

**Pull request merged**
