### PR TITLE
feat(tangle-dapp): Create table listing liquid staking pools

### LINKED ISSUE #2528: [FEAT] Create table listing liquid staking pools
- Liquid staking in the Parachain will utilize the concept of "pools" rather than individual validators.
- During liquid staking, a table listing all the available pools should be shown, which would allow the user to select which pools to stake onto.
- Each table row should show the relevant pool information, such as what validators are within it, the pool owner, total value staked, APY, and any other relevant information.
- Each pool is unique regardless of its validators; for example, there can be two pools with the same validator set, and still be considered different.
- Note that the Liquifier smart contract (deployed on Ethereum Mainnet) does not support pools as of now, so the validator table should still be shown for it.

### PR DESCRIPTION
**Pull request by yurixander**
## Summary of changes

_Provide a detailed description of proposed changes._

- ➕ Implemented a table listing all available liquid staking pools, fetched from Tangle.
- ➕ For each pool row in the table, various properties are derived, including the owner's address/avatar, its nominations, the total amount staked (TVL), the owner's stake, commission, pool metadata/name, and APY.
- ➕ Added an error/warning state, in case that the user attempts to load pools in a network that is outdated or doesn't support liquid staking pools yet (ie. mainnet).

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2528

### Screen Recording

_If possible provide a screen recording of proposed change._

Screenshot 2024-09-15 at 23 47 36

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by yurixander** [comment]
What's left here: Need to calculate the APYs for the liquid staking pools, since this is a crucial piece of data. This calculation, however, is a bit more complex than the others, since calculating the compound APY requires historical data, which has to be derived from the available query APIs.

**Comment by yurixander** [comment]
I've derived & calculated the APY of pools. Next, I just need to link the selected row/pool with the liquid stake call, and this PR should be good to go.

**Review by AtelyPham — APPROVED** [review]

**Comment by drewstone** [comment]
If we need another release for to get this PR in as well, push another @AtelyPham

**Comment by AtelyPham** [comment]
> If we need another release for to get this PR in as well, push another @AtelyPham

Yuri is updating the liquid staking in response to recent changes to the pool. Once he completes this task, we will release an update for liquid staking.

**Pull request merged**
