### PR TITLE
Marketing mobile view and email subsription

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
- Adding mobile view for the marketing page
- Update the loop hero animation
- Update new animations in the "Privacy connected" section
- Update new illustrations in the "Privacy scale" section
- Update and organize the text and illustrations in the "Application & Development" section
- Integrate Sendinblue email subscriptions 

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/webb-dapp/issues/809
- Closes https://github.com/webb-tools/webb-dapp/issues/816

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### Additional info

To get Sendinblue working, we have to set the API key environment variable on the server. 

cc: @dutterbutter @drewstone 

```
SENDINBLUE_API_KEY="API KEY HERE"
```

### Screen recording

https://user-images.githubusercontent.com/60747384/210650697-ab2f94e8-4ef6-4a68-8d63-d833bfaa0adc.mp4

### CODE REVIEW

**Comment by drewstone** [comment]
Lots of merge conflicts here, but great work! CC @seeddisperser @monaiuu for design audit/review

**Comment by AtelyPham** [comment]
> Lots of merge conflicts here, but great work! CC @seeddisperser @monaiuu for design audit/review

My bad! I'll resolve rn!

**Comment by seeddisperser** [comment]
Looking great @AtelyPham! 

Updates:
I've added [error and success states to the footer component](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1640%3A47159&t=zpBPBbPS1ekDFzxY-1)
The [assets](https://www.figma.com/file/d5T0P9k4anUGdBlqgh4ueW/%F0%9F%96%A5%EF%B8%8F-Webb-Website?node-id=1038%3A48719&t=zpBPBbPS1ekDFzxY-1) in the research and development section have bee slightly modified.

And a few edits:

- a drop shadow should be added to the nav bar once the page is scrolled. I think I saw you were working on adding this.
Screenshot 2023-01-04 at 5 04 37 PM
- "Scaling Privacy for everyone..." should have no padding, and should be inline with the other elements
Screenshot 2023-01-04 at 5 07 53 PM
- The illustration should not scale. This should be the breakpoint for the layout to change from two columns to one column.
Screenshot 2023-01-04 at 5 10 13 PM

A few notes to myself
- I need to fix the blur on the DAI coin in the hero animation
- when the paragraph width is fixed we need to be careful that the copy doesn't leave a single word hanging on a line.

**Comment by monaiuu** [comment]
Looks great!

A couple notes on the mobile version:

* This section looks a bit odd, I think the animation graphics needs to be bigger somehow, and there isn't enough gap between the animation and the next section.
 image

* There is too much divide/gap between the texts and these animations. User is unable to view the text content alongside with the animations below. 
image
image

**Comment by devpavan04** [comment]
Can we keep the container static while switching between the tabs to avoid this? @AtelyPham 

https://user-images.githubusercontent.com/53374218/210814857-c7445c00-474d-4620-ac82-261e844f8cef.mov

**Comment by dutterbutter** [comment]
@AtelyPham added `env` variable to server

**Comment by dutterbutter** [comment]
@AtelyPham resolved deployment issue!

**Comment by dutterbutter** [comment]
hmm looks like the nextjs runtime plugin is not picked up on manual deployments using netlify CLI....site deploys correctly via UI but not here. I will continue to investigate.

**Comment by dutterbutter** [comment]
@AtelyPham I am still having issues with this deployment issue, I have made a detailed post [here](https://stackoverflow.com/questions/75062659/netlify-cli-nextjs-runtime-deployment-fail-to-find-page) asking the community for help as well as on the netlify forum. 

Will follow up with other relevant updates. This is NOT a blocker for this PR to be merged as the deployment on `develop` via the UI works as intended.

**Review by dutterbutter — APPROVED** [review]

**Pull request merged**
