### PR TITLE
Leaderboard - Adding Sessions and Identity Info, Support Search Functionality

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes

_Provide a detailed description of proposed changes._

- Fix the parsing error due to backend updated
- Adding sessions and identity info
- Support search functionality

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [x] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

- Closes https://github.com/webb-tools/webb-dapp/issues/1860
- Closes https://github.com/webb-tools/webb-dapp/issues/1859

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/60747384/f652e455-ad95-4227-96d5-9ebac24f4f09

### CODE REVIEW

**Comment by devpavan04** [comment]
@AtelyPham Fixed - ranking numbers remain fixed despite changes in table pagination.


https://github.com/webb-tools/webb-dapp/assets/53374218/fc55c874-52f2-4d26-bd99-5757f0a9f1fe

**Comment by AtelyPham** [comment]
I think the address is fine, we both agree on the design and implementation we will display the address, if you want to display the display name, maybe show it somewhere instead of replacing the address field. @devpavan04

**Comment by monaiuu** [comment]
I think @devpavan04 suggested displaying identity rather than address is due to consistency with EVM staking validators display. Perhaps we could enable the identity to open up explorer to view the address, wdyt?

**Comment by devpavan04** [comment]
@monaiuu We cannot access individual account pages on Polkadot apps. Try accessing this [link](https://polkadot.js.org/apps/?rpc=wss://rpc.tangle.tools#/staking) and click on any validator. Validator information will be displayed in a side panel, which does not change the URL. In the EVM staking app, the validator table has an external link icon; when clicked, it redirects to the staking overview page and not to the validator's information page. Perhaps we should replace the external link icon with copy icon in the EVM staking app, so that users can copy the address/identity name and search. Wdyt?

**Comment by monaiuu** [comment]
> @monaiuu We cannot access individual account pages on Polkadot apps. Try accessing this [link](https://polkadot.js.org/apps/?rpc=wss://rpc.tangle.tools#/staking) and click on any validator. Validator information will be displayed in a side panel, which does not change the URL. In the EVM staking app, the validator table has an external link icon; when clicked, it redirects to the staking overview page and not to the validator's information page. Perhaps we should replace the external link icon with copy icon in the EVM staking app, so that users can copy the address/identity name and search. Wdyt?

Yup sounds good to me.

**Comment by drewstone** [comment]
yea if there's no identity its perfect to just show the address

**Comment by drewstone** [comment]
Is this ready for merge? If we're making any more changes, I'd like to request we give more space to the "Address" section so that we can show as much of the identity display name as possible instead of cutting it off.

**Pull request merged**
