### PR TITLE
Faucet App

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
_Provide a detailed description of proposed changes._
- Implementation full UI using mocked logic.
- Upgrade to Next.js 13.2
- Moved `Navbar` to `webb-ui-kit` to share between apps.
- Moved links into `dapp-config` and export as default to use as a separate module to share between apps.
- Other UI fixes.

## Command to run the Faucet app

- Serve the Faucet app (for development): `yarn nx serve faucet`
- Build the Faucet app: `yarn nx build faucet`
- Export static files of the Faucet app: `yarn nx export faucet`

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [x] `apps/webbsite`
- [x] `apps/faucet`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes https://github.com/webb-tools/webb-dapp/issues/1030

### Screen Recording
_If possible provide a screen recording of proposed change._

https://user-images.githubusercontent.com/60747384/228052275-714bce9b-c774-49bc-8fb8-f130cd5819bc.mp4

### CODE REVIEW

**Comment by dutterbutter** [comment]
deploy preview failing seems to be ` ›   TypeError: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined` . 

Could be due to next.js bump?

**Comment by dutterbutter** [comment]
@AtelyPham can we add the following commands into the root package.json please:

```

**Comment by dutterbutter** [comment]
Investigating the deployment issue with the webbsite, it seems that the build command (e.g. `yarn build:webbsite`) no longer creates a `.next` directory?

**Comment by AtelyPham** [comment]
Revert to `next@13.1.1` works fine, it seems like `nx` does not support `next@13.2.4` very well 🤔 I'll continue investigating.

**Comment by monaiuu** [comment]
A quick UI review:

- There are dark drop shadows on all components on the main card component, any way to remove them? Please see below comparison between figma file & deployed preview for reference:
Screenshot 2023-03-29 at 4 52 44 PM

- Could we apply a linear white gradient using the info below for the main card component?
Screenshot 2023-03-29 at 5 03 15 PM

For some contexts, here is how the gradient was created in figma:
Screenshot 2023-03-29 at 5 03 39 PM

Let me know if there is any question!

**Pull request merged**
