### PR TITLE
footer is now bottom bound

### LINKED ISSUE #1097: [TASK] Ensure Footer Component is Bottom Bound
## Description

Ensure the footer component remains bottom-bound in all supported browsers/windows, regardless of the browser height. 

### Screenshot

Image

(For reference: In cbridge, the footer component is currently bottom bound, and remains fixed to the bottom of the page regardless of the height of the browser window.)

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes
_Provide a detailed description of proposed changes._
- 

### Proposed area of change
_Put an `x` in the boxes that apply._

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)
Closes #1097 

### Screen Recording
_If possible provide a screen recording of proposed change._

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by dutterbutter** [comment]
@vutuanlinh2k2 let's also make the footer the minimal version, which is just the social tags as depicted in the issue.

**Review by AtelyPham — APPROVED** [review]
LGMT 👍!

**Review by AtelyPham — CHANGES_REQUESTED** [review]
Oops, I forgot the light mode, the background color looks a bit odd here! @vutuanlinh2k2 

CleanShot 2023-05-10 at 21 03 47@2x

**Comment by dutterbutter** [comment]
Dark theme is off: @vutuanlinh2k2 

CleanShot 2023-05-11 at 08 04 45@2x

**Comment by dutterbutter** [comment]
@monaiuu can you review this when you can please. The design aesthetics of the minimal footer does not seem fitting. Would like your thoughts.

**Comment by monaiuu** [comment]
## Footer Update

Please reference to the Figma design system ([footer page](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?type=design&node-id=38%3A364&t=UTYpo9oUdhBrOd0b-1))for the updated footer component on both light and dark mode.

For some context, we will remove the background colour of the footer component in anticipation of the updated swirl background image. 

### Screenshots
Screenshot 2023-05-12 at 12 38 51 PM


Screenshot 2023-05-12 at 12 40 05 PM

@vutuanlinh2k2 @dutterbutter

**Comment by drewstone** [comment]
There seems to also be a bug (unsure if introduced here) with respect to light/dark theme switching.

https://www.loom.com/share/d688378cf6bc42bf936e120cc938404a

**Comment by drewstone** [comment]
Is this ready to merge do @AtelyPham ?

**Review by AtelyPham — APPROVED** [review]
LGMT 👍!

**Pull request merged**
