### PR TITLE
ci(repo): ESM Migration & Bump Deps

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes

*Provide a detailed description of proposed changes.*

- [x]  Removed unused anchors & signature bridge addresses in the config.
- [x]  Migrated to Nx v19 which supports ESM migration and utilizes [`nx-release`](https://nx.dev/features/manage-releases) to improve the release process.
- [x]  Migrated all libraries to ESM:
    - [x]  Updated the `rollup` build with consistent bundles & types.
    - [x]  Updated the `tsc` build for consistent bundles & types.
- [x]  Migrated apps to ESM
    - [x]  Migrated webpack apps to ESM
    - [x]  Investigated the Nextjs migration to ESM but unfortunately, `@nx/next` plugin is not yet supported in ES modules
        - See [https://github.com/nrwl/nx/issues/15682](https://github.com/nrwl/nx/issues/15682)
        - See [https://github.com/nrwl/nx/issues/23048#issuecomment-2120106231](https://github.com/nrwl/nx/issues/23048#issuecomment-2120106231)
- [x]  Updated minimum requirement engines
    - Node `>=18.12.x`
    - Yarn `4.2.2`
- [x]  Bumped ***88*** dependencies & ***164*** dev dependencies with breaking changes
- [x]  Upgraded to Storybook v8.1.1 with breaking changes
- [x]  Removed Sentry on apps
- [x]  Upgraded github action packages with breaking changes
- [x]  Migrated to wagmi v2
- [x]  Fixed the `secondaryMessage` not showing on the notification
- [x]  Fixed rainbow wallet connection
- [x]  Handled wallet not installed error with multiple injected providers by utilizing **[EIP-6963](https://eips.ethereum.org/EIPS/eip-6963)** providers
- [x]  Migrated to Eslint v9 & Prettier v3
    - Tried flat config feature of eslint v9 but it seems nx still not supported flat config with esm modules pretty well!
- [x]  Replaced built-in hooks with hooks from a library
- [x]  Migrated to Modern Yarn v4

### Instruction to migrate to Modern Yarn v4 (cc @yurixander @devpavan04 @vutuanlinh2k2)

1. Make sure the minimum Node requirement `>=18.12.x`
2. Run `corepack enable` to activate [Corepack](https://nodejs.org/api/corepack.html)
3. Go into your project directory
4. Run `yarn set version 4.2.2`

For more information about the migration, refer to the Yarn [documentation](https://yarnpkg.com/migration/guide#migration-steps).

### Proposed area of change

*Put an `x` in the boxes that apply.*

- [x]  `apps/bridge-dapp`
- [x]  `apps/hubble-stats`
- [x]  `apps/stats-dapp`
- [x]  `apps/tangle-dapp`
- [x]  `apps/testnet-leaderboard`
- [x]  `apps/faucet`
- [x]  `apps/zk-explorer`
- [x]  `libs/webb-ui-components`

### Reference issue to close (if applicable)

*Specify any issues that can be closed from these changes (e.g. `Closes #233`).*

- Closes [https://github.com/webb-tools/webb-dapp/issues/2312](https://github.com/webb-tools/webb-dapp/issues/2312)
- Related [https://github.com/webb-tools/webb-dapp/issues/2250](https://github.com/webb-tools/webb-dapp/issues/2250)

### CODE REVIEW

**Comment by AtelyPham** [comment]
The current build time of the `webb-ui-component` is not optimal; it takes around 30 minutes to build the library 🥲. I investigated and tried many approaches to optimize the build time over the last weekend.

Rollup doesn't work very well with bundling the project's dependencies. I've tried many ways to optimize Rollup's build time but haven't come up with an optimal solution.

So, I decided to move to Vite to build the `webb-ui-components`. This will be handled in a separate PR and then merged into this PR.

**Comment by devpavan04** [comment]
### Transfer (Substrate address to Substrate address and Substrate address to EVM address) ✅ 


https://github.com/webb-tools/webb-dapp/assets/53374218/0f7a4311-9d43-4d25-8a54-89ff505b34c0

**Comment by devpavan04** [comment]
### First-time nominator (step 1 - select validators) runtime error ❌


https://github.com/webb-tools/webb-dapp/assets/53374218/85bf6b22-b31b-458b-a797-ced77d332a61


CleanShot 2024-05-30 at 08 27 50

**Comment by devpavan04** [comment]
### First-time nomination (Substrate) ✅ 

https://github.com/webb-tools/webb-dapp/assets/53374218/7299aca4-cc37-4a2d-a3ad-4ddab5d48ccd

**Comment by devpavan04** [comment]
### Add stake -bond extra (Substrate) ✅ 


https://github.com/webb-tools/webb-dapp/assets/53374218/a85833db-937a-4c9c-9b37-d263bef12b48

**Comment by devpavan04** [comment]
### Unbond (Substrate) ✅ 

https://github.com/webb-tools/webb-dapp/assets/53374218/0407ecdc-0d33-4347-8278-06b70647d74f

**Comment by devpavan04** [comment]
### Rebond (Substrate) ✅ 

https://github.com/webb-tools/webb-dapp/assets/53374218/9ef83eb9-b0c7-413c-83d4-7452d83783e6

**Comment by devpavan04** [comment]
### Change reward destination (Substrate)

https://github.com/webb-tools/webb-dapp/assets/53374218/769066f2-6fbb-47e1-af37-b0485fede46f

**Comment by devpavan04** [comment]
### Stop nomination (Substrate) ✅ 

https://github.com/webb-tools/webb-dapp/assets/53374218/9ed2f247-f83d-45d2-b309-d5093c281824

**Comment by yurixander** [comment]
EVM transaction QA checklist:
- [ ] Setup nominator
- [ ] Bond more
- [ ] Set payee
- [ ] Unbond
- [ ] Rebond
- [ ] Withdraw
- [ ] Transfer EVM -> Substrate
- [ ] Transfer EVM -> EVM

**Review by devpavan04 — APPROVED** [review]

**Review by yurixander — APPROVED** [review]

**Pull request merged**
