### PR TITLE
feat(tangle-dapp): Implement updated design for LS pools

### LINKED ISSUE #2568: [FEAT] Update liquid staking design impl. to accomodate LS pools
To accomodate the new liquid staking system (pools), there are a few design changes that need to be made to make the liquid staking process feel more natural. This includes:
- [ ] Creating a new table that lists the pools which the active user has stake in,
- [ ] Showing a separate table that lists all available pools
  - [ ] Per row (pool), there should be a `Stake` button that **sets the selected token** on the liquid staking card. In other words, when the user finds a pool they like, they click the `Stake` button, and the liquid staking card sets that pool/token as the selected token.
- [ ] Options & actions for pool administrators. This will be implemented in the form of a dropdown of buttons, each representing a pool management action.
  - [ ] If the active user has the `nominator` role for a given pool, the `Manage` button dropdown will show a `Update nominations` action, which when clicked will reveal a modal to update the pool's nomination.
  - [ ] The same idea applies for the other roles: `root` (able update roles), and `bouncer`.
  
CC @monaiuu

### LINKED ISSUE #2569: [FEAT] Liquid staking pool creation flow
The liquid staking pool creation process should be relatively simple and straightforward to implement:

- [x] When the user clicks the `Create pool` button, a modal with the following options should display: `name`, `amount`, `token`, `root address`, `nominator address`, `bouncer address`, and `commission`.
- [x] On the modal, when the user confirms the transaction, that should simply call the `lst::create` extrinsic in the case of Tangle mainnet/testnet/local dev.
- [ ] ~~Since `name` and `commission` are set through independent extrinsics, the process can be simplified by batching the pool creation event with 3 extrinsics: 1. create the pool, 2. set the name, 3. set the commission. This would be done under the hood as an implementation detail.~~

CC @monaiuu

### PR DESCRIPTION
**Pull request by yurixander**
## Summary of changes

_Provide a detailed description of proposed changes._

- ➕ Added a new table which lists LS pools that the **user is involved in: either via management roles, or staked in**. This provides a quick view on how the pools which you've staked on are performing (APY), and also management actions in case you have management roles.
- ➕ The action button's text will change depending on the action that the user will take. For example, if the user is about to stake on a pool in which they already have a stake in, it'll show `Increase Stake`, otherwise `Stake`.
- ➕ Added various table states for the LS pool tables: Loading, error, and empty.
- ➕ Implemented onboarding modal logic, and also onboarding modal for the liquid staking page (see #2577).
- ➕ Added OpenGraph page metadata to the Liquid Staking page.
- 🔧 Simplified liquid staking pages: Instead of having an overview page, both liquid staking & overview page will now live in a single page for a more streamlined UX.
- 🖌️ Adjusted design of the pools table and simplified interaction & pool selection process.
- ⚠️ Restaking Parachain LS protocol handling hasn't yet been adjusted since there are still changes that need to be made on the parachain, such as associating every pool with a single token (ie. DOT, PHA, etc.). CC @1xstj

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2568

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/user-attachments/assets/30a68c7d-11b4-45fe-9ed1-1dc935f4a9ab

Screenshot 2024-10-04 at 06 45 50
Screenshot 2024-10-04 at 05 50 54
Screenshot 2024-10-04 at 04 25 43

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by yurixander** [comment]
> ⚠️ Restaking Parachain LS protocol handling hasn't yet been adjusted since there are still changes that need to be made on the parachain, such as associating every pool with a single token (ie. DOT, PHA, etc.). CC @1xstj

CC @1xstj

**Review by drewstone — APPROVED** [review]
Looks good, my only nit is that I think we should be making numeric values font size larger. There's a few areas that looks so tiny and my eyes strain looking at them! CC @monaiuu.

**Review by AtelyPham — APPROVED** [review]

**Comment by drewstone** [comment]
Let's cut a release! @yurixander @AtelyPham

**Comment by yurixander** [comment]
> Let's cut a release! @yurixander @AtelyPham 

Yep. I'll also see if I can get the pool creation flow in today or tomorrow.

**Pull request merged**
