### PR TITLE
chore: update claim page faq copy

### PR DESCRIPTION
**Pull request by monaiuu**
## Summary of changes

_Provide a detailed description of proposed changes._

- update copy within FAQ section for Tangle Airdrop Claim page 

@vutuanlinh2k2 or @devpavan04  could you assist me with adding URL links to mentions of [Edgeware](https://www.edgeware.io/) and [Tangle Testnet Leaderboard](https://leaderboard.tangle.tools/) within the section? 

Screenshot 2024-02-14 at 3 49 09 PM
Screenshot 2024-02-14 at 3 49 15 PM
Screenshot 2024-02-14 at 3 49 20 PM

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes

### Screen Recording

_If possible provide a screen recording of proposed change._

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by vutuanlinh2k2** [comment]
@monaiuu can you show me where to add those links

**Comment by monaiuu** [comment]
> @monaiuu can you show me where to add those links

Add https://www.edgeware.io/ to `Edgeware`.
Screenshot 2024-02-16 at 9 40 28 AM

Add https://leaderboard.tangle.tools/ to `Tangle Incentivized Testnet Campagin` & `Tangle Testnet Leaderboard`. 
Screenshot 2024-02-16 at 9 41 20 AM

(I was unsure how to do it since the FAQ file is in `.ts` rather than `.tsx` format)

**Comment by yurixander** [comment]
Idea: We may want to move away from defining the FAQ as a constant, and maybe use React components, ie. `FAQItem` especially if we want embedded things on its contents, like links:

```tsx
<FAQItem title="Some title here">
  Some content here<br />
  <a href="#">Learn more</a>
</FAQItem>
```

I do think that the constant approach keeps it more centralized, but it may not be as beneficial if the content/FAQ items won't be changing regularly.

**Review by yurixander — APPROVED** [review]

**Comment by drewstone** [comment]
CC @thomivy for extra checking (PR any new updates)

**Pull request merged**
