### PR TITLE
Connect button opens chain selection card

### LINKED ISSUE #819: [BUG] The Connect Wallet Button does not open the Chain Selection Card
**Describe the bug**
When a new user comes to the dApp, if he/she hits the connect wallet button, then he/she closes the chain selection modal. After that, the connect wallet button on the card does not work (cannot open the Chain Selection card), he/she has to change the tab to trigger the component rendering to reset the state of the connect wallet button.

**To Reproduce**
1. Go to dApp
2. Click on the `Connect Wallet` button
3. Close the Chain Selection modal
4. Then, if you hit the `Connect Wallet` button, it does not work. You have to change the tab to trigger a re-rendering to let the button work again.

**Expected behavior**
The `Connect Wallet` button should always open the chain selection card when a user hits the button.

### Screen Recording

https://user-images.githubusercontent.com/60747384/207516257-b62e63e2-8982-4139-b76d-d954a067e019.mp4

### PR DESCRIPTION
**Pull request by devpavan04**
## Summary of changes
- Chain selection card is opened every time upon clicking the connect button. 

### Reference issue to close (if applicable)
- Closes #819 

https://user-images.githubusercontent.com/53374218/208578453-56a0d0d7-ab44-4b01-8d54-df31f0c2467a.mov

### CODE REVIEW

**Comment by dutterbutter** [comment]
@devpavan04 can we actually avoid having to open the chain selection component and instead make Goerli the default provider initially. Eliminating the need to go through the chain selection component unless they intentionally want to change source chains. Does that make sense?

**Comment by devpavan04** [comment]
### Changes Overview

-  Upon clicking `Connect Wallet` button, the `chain selection` step is skipped and the user will be prompted to select their choice of wallet to connect to the default chain i.e `Goerli`
- Addresses this comment https://github.com/webb-tools/webb-dapp/pull/831#issuecomment-1361506391

https://user-images.githubusercontent.com/53374218/209149906-834c4abc-3fd4-4897-8459-ac9ef0a4f9eb.mov

- Disconnect button is now working
- Closes #804 
- Closes #723 

https://user-images.githubusercontent.com/53374218/209150269-1b49896c-09a2-4093-b4a0-38555cead8e6.mov

- `Connect Wallet` button is now prompted when the user disconnects the account manually within the wallet.
- Closes #837

https://user-images.githubusercontent.com/53374218/209151104-ec9c946b-53b9-4c2f-9b64-325c394ba83c.mov

**Comment by devpavan04** [comment]
### Changes Overview

- `Download Now` button in wallet modal takes user to the metamask browser extension download link page.
- Closes #778 

https://user-images.githubusercontent.com/53374218/209161845-536bb3a5-2de7-44bc-a83e-9287309500a4.mov

**Comment by devpavan04** [comment]
### Changes Overview

- `Switch` button now prompts user the metamask popup to change/select a new account instead of prompting the user to switch to a different chain.
- Closes #805 

https://user-images.githubusercontent.com/53374218/209169667-affb505c-594c-4ac6-a1eb-8c5359656849.mov

**Review by drewstone — APPROVED** [review]
LG!

**Comment by devpavan04** [comment]
### Changes overview

@AtelyPham @dutterbutter 

- Removes `app` config from `localstorage` on wallet disconnect.

https://user-images.githubusercontent.com/53374218/209250193-7afdf7fc-8bc8-472c-abd4-65d86148d4b8.mov

**Pull request merged**
