### PR TITLE
Standardize Asset and Network treatment

### LINKED ISSUE #1282: [TASK] Standardize Asset and Network treatment
## Description
Please update the network's treatment to distinguish from tokens to improve clarity and standardize how elements are represented. 

Image

- For `token` representation, we will remain using `circular` shapes to represent tokens.

- For `network/chain` representation, we will update to a `rectangular` shape to represent networks.

- To align with this update, the `chain chips` previously implemented will require an update to their `radius` to align with the chain representation.

### Design System Updates
These components have been added to the design system; please reference the following pages for reference:

- **'🟢  [Avatars](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=30%3A352&t=zL5xxCWbLFEeiJRw-1)'** for added relayers and shielded token/pools treatment.
Image

- **'🟢  [Chain Icons](https://www.figma.com/file/H43lYnTCOAPjO9kTrrepe1/%F0%9F%95%B8%EF%B8%8F-Design-System?node-id=4746%3A101498&t=zL5xxCWbLFEeiJRw-1)'** for updated chain icon display & chain chips display.
Image

Please note for this update, we will also have to ensure all dependent components are updated accordingly. I have audited and reviewed the entire design system and updated the component treatments accordingly. This update has also been pushed and should now similarly apply to all project files within Figma.

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

- Update Stories for ChainIcon and ChainChip component
- Update ChainIcon from circle shape to rounded square shape
- Refactor Avatar components

### Proposed area of change
_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)
_Specify any issues that can be closed from these changes (e.g. Closes #233)._
- Closes #1282 

### Screenshots
Screenshot 2023-06-29 at 11 43 46

https://github.com/webb-tools/webb-dapp/assets/69841784/15dd25dd-60fc-4123-9238-85f09be95154

-----
### Code Checklist 
_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by monaiuu** [comment]
Can I get access to the following preview to review this update:

- Hubble Bridge
- DKG stats page
- Storybook documentation

**Comment by AtelyPham** [comment]
> Can I get access to the following preview to review this update:
> 
> * Hubble Bridge
> * DKG stats page
> * Storybook documentation

Yes, let my find that for you.

**Comment by drewstone** [comment]
What's the status of the review here @monaiuu ? Did you get the links you needed?

**Comment by AtelyPham** [comment]
* [Storybook](https://63c82af0a12ff0654738ca00-visyhhoddn.chromatic.com/?path=/docs/design-system-molecules-chainchip--docs)
* [DKG stats page](https://649dd1dcf7a3b51cf0eac06d--development-stats.netlify.app/#/keys)
* [Hubble Bridge](https://649dd2268e3ccb20340b32e7--development-hubble-bridge.netlify.app/#/bridge)

Sorry for the delay cc @monaiuu.

**Review by AtelyPham — APPROVED** [review]
The code LGTM 👍 It seems you missed the Orbit chain icons @monaiuu.

**Comment by AtelyPham** [comment]
The current Orbit chain icon is [here](https://github.com/webb-tools/webb-dapp/blob/develop/libs/icons/src/chains/athena-orbit.svg) @monaiuu.

**Comment by AtelyPham** [comment]
New deploy preview with Orbit chains included.

* [Storybook](https://63c82af0a12ff0654738ca00-njsvexguli.chromatic.com/?path=/docs/design-system-molecules-chainchip--docs)
* [DKG stats page](https://649def7ab721ca36587b5d46--development-stats.netlify.app/#/proposals)
* [Hubble Bridge](https://649defb91eaf262f4b139a7f--development-hubble-bridge.netlify.app/#/bridge)

**Review by monaiuu — APPROVED** [review]

**Pull request merged**
