### PR TITLE
feat(tangle-dapp): Display Balance in Bridge on Tangle Dapp

### LINKED ISSUE #2330: [TASK] Display Balance of the bridging token

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
_Provide a detailed description of proposed changes._

- Display Selected Token Balance  for different cases: EVM Native, EVM Erc20, and Substrate
- Handle source chain and mismatch scenarios
- Update `InfoIconWithTooltip` component across dapps
- Update `ScrollAlpha` to `ScrollSepolia`

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [x] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [x] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [ ] `apps/zk-explorer`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. `Closes #233`)._

- Closes #2330 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/ca6fcdcf-5687-4e57-b36f-7d118086c7be

#### Mismatch case (User can choose wallets that only support the source chain)

https://github.com/webb-tools/webb-dapp/assets/69841784/cbdcd79c-487e-4225-a2a6-38d2b36f49d9

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by monaiuu — CHANGES_REQUESTED** [review]
Unify balance label display as `Balance` (substitute `Transferable`) across networks. 
Screenshot 2024-05-28 at 7 03 31 PM
Screenshot 2024-05-28 at 7 03 19 PM

**Comment by vutuanlinh2k2** [comment]
> Unify balance label display as `Balance` (remove `Transferable`) across networks for consistency. Screenshot 2024-05-28 at 7 03 31 PM Screenshot 2024-05-28 at 7 03 19 PM

@monaiuu each chain will have different number of decimals (Ethereum: 18, Polkadot: 10, etc.) What I'm displaying here is the full amount that is allowed by each chain for the best precision

**Comment by monaiuu** [comment]
> > Unify balance label display as `Balance` (remove `Transferable`) across networks for consistency. Screenshot 2024-05-28 at 7 03 31 PM Screenshot 2024-05-28 at 7 03 19 PM
> 
> @monaiuu each chain will have different number of decimals (Ethereum: 18, Polkadot: 10, etc.) What I'm displaying here is the full amount that is allowed by each chain for the best precision

I meant in Tangle Testnet Native we use the term 'Transferable', but other networks we use the term 'Balance'. I think it is ok to unify the display to 'Balance' for all networks.

**Comment by vutuanlinh2k2** [comment]
> > > Unify balance label display as `Balance` (remove `Transferable`) across networks for consistency. Screenshot 2024-05-28 at 7 03 31 PM Screenshot 2024-05-28 at 7 03 19 PM
> > 
> > 
> > @monaiuu each chain will have different number of decimals (Ethereum: 18, Polkadot: 10, etc.) What I'm displaying here is the full amount that is allowed by each chain for the best precision
> 
> I meant in Tangle Testnet Native we use the label 'Transferable', but other networks we use the label 'Balance'. I think it is ok to unify the display to 'Balance' for all networks.

Oops I misread so sorry

**Review by monaiuu — COMMENTED** [review]
Thoughts on updating the button text to prompt user to switch to different wallet type if mismatch with source chain instead of using error texts? 

Screenshot 2024-05-28 at 7 18 01 PM

**Comment by vutuanlinh2k2** [comment]
> Thoughts on updating the button text to prompt user to switch to different wallet type if mismatch with source chain instead of using error texts?
> 
> Screenshot 2024-05-28 at 7 18 01 PM


@monaiuu I just updated the video preview for this case on the top description, let me know what you think

**Comment by monaiuu** [comment]
Also 

> > Thoughts on updating the button text to prompt user to switch to different wallet type if mismatch with source chain instead of using error texts?
> > Screenshot 2024-05-28 at 7 18 01 PM
> 
> @monaiuu I just updated the video preview for this case on the top description, let me know what you think

Ok this works. Can we update the button text to 'Switch Wallet' instead of 'Connect' for clarity? (since user has already connected wallet)

**Comment by vutuanlinh2k2** [comment]
> > > Thoughts on updating the button text to prompt user to switch to different wallet type if mismatch with source chain instead of using error texts?
> > > Screenshot 2024-05-28 at 7 18 01 PM
> > 
> > 
> > @monaiuu I just updated the video preview for this case on the top description, let me know what you think
> 
> Ok this works. Can we update the button text to 'Switch Wallet' instead of 'Connect' for clarity? (since user has already connected wallet)

Updated:
CleanShot 2024-05-28 at 21 28 46@2x

**Review by yurixander — APPROVED** [review]

**Comment by drewstone** [comment]
Does anyone find it odd that this feature requires so many file updates? I imagine we have a lot of room for improvement and code reuse, no? I see the bridge app uses hooks that likely can be shared across all apps?

**Comment by yurixander** [comment]
> Does anyone find it odd that this feature requires so many file updates? I imagine we have a lot of room for improvement and code reuse, no? I see the bridge app uses hooks that likely can be shared across all apps?

@drewstone Most file changes are due to the refactoring of the `InfoIconWithTooltip` component which was moved to the shared lib, and also the renaming of a chain config used in some files. The actual changes look reasonable

For the hooks, I would say keeping the newly introduced ones specific to the bridge as they are in this PR is likely the best for now, since they have specific & simple logic for bridge

**Comment by vutuanlinh2k2** [comment]
The CI is failing because it takes too long to install dependencies. Need to merge this [PR](https://github.com/webb-tools/webb-dapp/pull/2331) first

**Comment by AtelyPham** [comment]
Restarted the CI, it is building now.

CleanShot 2024-05-31 at 14 01 37@2x

**Comment by AtelyPham** [comment]
@vutuanlinh2k2 The build failed with this error.

CleanShot 2024-05-31 at 14 09 09@2x

**Review by AtelyPham — APPROVED** [review]
The CI is still failing @vutuanlinh2k2.

**Pull request merged**
