### PR TITLE
GitHub section collapsible on Project Detail Page on Zk Explorer

### LINKED ISSUE #1826: [FEAT] Implement Project Overview Page
## Description

To implement an overview page for uploaded ZK project and its associated circuits. This page will present detailed information fetched from the GitHub API, complemented by user-contributed data, to provide an in-depth look at the project & circuit's characteristics. The Project Overview Page serves as an in-depth view for individual circuits within a project, providing users with detailed information about the circuit, including source code, metadata, and trusted setup info. 

## Project Overview Page
**Project Header**
- Display the project's name and the associated GitHub username or organization.
- Include an icon button to view the project on GitHub next to project name.
- Display social links (X, website, discord etc.) associated with the project.
- Display relevant tags for each project.

**Project Info Container**
- Fetch and display project metadata such as the project image, name, author, contributors, and other relevant details as shown in the screenshot.

**Project GitHub Container**
- Display GitHub-related data of the project (contributors, releases, etc.)
- Enable Project Info Container to be hidden or displayed via toggle (see below video). 

**Project Information Section Tabs**
- [x] #1836 
- [x] #1833 
- [x] #1834
- [x] #1835 
- [x] #1914 
- [x] #1915 
- [x] #1916 

### Screenshot
Screenshot 2023-12-19 at 11 53 27 AM

https://github.com/webb-tools/webb-dapp/assets/109539270/17052ce7-fccd-4257-b74c-a5200e33e19f

### LINKED ISSUE #1914: [TASK] Make GitHub Section in Project Detail page collapsible
The GitHub section on the Project Detail page's left side must be collapsible. When hovering on the section, an arrow appears to allow users to collapse the section. This is for a more ‘focused’ view to read through the info in the main section.

[**FIGMA LINK**](https://www.figma.com/file/YdAvVIAmv0VGAigJmAAjAJ/%E2%9A%97%EF%B8%8F--ZK-Explorer?type=design&node-id=150-39401&mode=dev)

Image

### PR DESCRIPTION
**Pull request by vutuanlinh2k2**
## Summary of changes

_Provide a detailed description of proposed changes._

- GitHub section collapsible on ProÏject Detail Page on Zk Explorer

### Proposed area of change

_Put an `x` in the boxes that apply._

- [ ] `apps/bridge-dapp`
- [ ] `apps/hubble-stats`
- [ ] `apps/stats-dapp`
- [ ] `apps/tangle-dapp`
- [ ] `apps/testnet-leaderboard`
- [ ] `apps/faucet`
- [x] `apps/zk-explorer`
- [ ] `libs/webb-ui-components`

### Reference issue to close (if applicable)

_Specify any issues that can be closed from these changes (e.g. Closes #233)._

- Closes #1914 
- Closes #1826 

### Screen Recording

_If possible provide a screen recording of proposed change._

https://github.com/webb-tools/webb-dapp/assets/69841784/c3cf16b5-ff35-450a-b2c8-dde6db52c94d

---

### Code Checklist

_Please be sure to add .stories documentation if any additions are made to `libs/webb-ui-components`._

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Review by yurixander — APPROVED** [review]
Looks good 🙂

**Comment by devpavan04** [comment]
Is the collapse arrow icon supposed to go all the way to the left of the screens when collapsed? Also, the icon should appear only when hovered I believe.


https://github.com/webb-tools/webb-dapp/assets/53374218/b32fb8d6-0268-4c28-afa2-884e6f3df9a2

**Comment by vutuanlinh2k2** [comment]
> Is the collapse arrow icon supposed to go all the way to the left of the screens when collapsed? Also, the icon should appear only when hovered I believe.
> 
>  CleanShot.2024-01-11.at.09.56.48.mp4

cc @monaiuu to check if the current design is ok with you yet. I let the arrow always show up because I think it is better for the user to know the section is collapsible even when they are not hovering on it

**Review by AtelyPham — COMMENTED** [review]
Left some comments.

**Review by AtelyPham — APPROVED** [review]

**Pull request merged**
