### PR TITLE
Setup Statistic Page as separate react app

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
- Move the tailwind config to root to sharable between repos
- Setup separate react app for `page-statistics`
- Setup the Keys page for the demo

### Reference issue to close (if applicable)
- Closes 

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### Screenshot

https://user-images.githubusercontent.com/60747384/189996825-b620277c-f073-4790-9070-d6f5bada0f7f.mp4

### CODE REVIEW

**Comment by AtelyPham** [comment]
Once this PR is merged, we ready to merge the `webb-ui-kit` into develop, then continue the work on the statistic page on the develop branch.

**Review by dutterbutter — COMMENTED** [review]
For the favicon and logo lets utilize the new logo instead of the old one please. This is awesome btw @AtelyPham !!

**Comment by AhmedKorim** [comment]
image

**Comment by AtelyPham** [comment]
It's `http://localhost:3000` with our mixer @AhmedKorim. And please use `yarn start:stats` instead of `yarn start:localDapp`.

**Comment by AhmedKorim** [comment]
Can we have this in the readme?

**Comment by AtelyPham** [comment]
Ok, let me update the `README` as well 👍

**Comment by AhmedKorim** [comment]
This works for me it seems the issue was in my setup, Great job @AtelyPham

**Pull request merged**
