### PR TITLE
VAnchor Substrate Withdraw and Transfer

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
- Fix Tangle script error due to `balances.ExistentialDeposit` error
- Commitments setup, fetching leaves for Polkadot Provider
- Implement VAnchor withdraw on the substrate side
- Implement VAnchor transfer on the substrate side
- UI crash in the `Avatar` component when no relayer is available
- Fix should filter available tokens by token symbol and target typed chain id from notes.

### Proposed area of change

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [ ] `apps/faucet`
- [ ] `apps/tangle-website`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/webb-dapp/issues/1372
- Closes https://github.com/webb-tools/webb-dapp/issues/1138
- Closes https://github.com/webb-tools/webb-dapp/issues/1119
- Closes https://github.com/webb-tools/webb-dapp/issues/1158

### Screen Recording

https://github.com/webb-tools/webb-dapp/assets/60747384/7479b920-836b-47a0-b42b-ae3a2974cab4

### CODE REVIEW

**Comment by AtelyPham** [comment]
> @AtelyPham how is this going? Looks like it's possibly going stale?

This is still blocked by the Circom proving work. I'll update this PR with the latest changes.

**Comment by AtelyPham** [comment]
Depends on https://github.com/webb-tools/webb-dapp/pull/1361.

**Comment by drewstone** [comment]
@AtelyPham what's the ETA for this?

**Comment by drewstone** [comment]
Awesome work @AtelyPham !

**Review by drewstone — APPROVED** [review]

**Pull request merged**
