### PR TITLE
Fixing Moonbase Alpha, Mumbai and Optimism Errors

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
_Provide a detailed description of proposed changes._
- Resolving remaining issues on Moonbase Alpha, Mumbai, and Optimism when depositing and withdrawing. 
- Sending the transaction to the relayer.
- Adding `defaultCategory` prop for the `ChainListCard` component.
- Adding the function to get transaction hash from an error if it exists
- Remove the `onDetail` function in the `TransactionQueueCard`
- Updating the latest create2 deployment
- Adding more RPC urls
- Refactor the switch and add chain steps in the `WebbProvider.tsx` when switching the chain
- Fixing small UI errors.

### Proposed area of change
_Put an `x` in the boxes that apply._

- [x] `apps/bridge-dapp`
- [ ] `apps/stats-dapp`
- [ ] `apps/webbsite`
- [x] `libs/webb-ui-components`

### Reference issue to close (if applicable)
- Closes https://github.com/webb-tools/webb-dapp/issues/992
- Closes https://github.com/webb-tools/webb-dapp/issues/964
- Closes https://github.com/webb-tools/webb-dapp/issues/937
- Closes https://github.com/webb-tools/webb-dapp/issues/935
- Closes https://github.com/webb-tools/webb-dapp/issues/931
- Closes https://github.com/webb-tools/webb-dapp/issues/939

### Screen Recording
_If possible provide a screen recording of proposed change._

https://share.cleanshot.com/tHnvvJ85

### CODE REVIEW

**Comment by dutterbutter** [comment]
@AtelyPham can you include this change https://github.com/webb-tools/webb-dapp/issues/992 in this PR?

**Comment by AtelyPham** [comment]
⚠️ This PR is still waiting for the live relayer to update the create2 and sync all the blocks. Then, PR can be tested and ready for review.

**Comment by dutterbutter** [comment]
@salman01zp please let us know when we can expect live relayer to update the create2 and sync all the blocks. Thanks!

**Comment by salman01zp** [comment]
We will be updating and making the relayer live today. It should be ready by Friday

**Comment by dutterbutter** [comment]
@AtelyPham given this PR has a lot of bug fixes, lets make use of the previous anchor addresses (e.g. the anchor addresses currently on `main`), go through deposit, withdraw, transfer flow to ensure it works as intended and deploy to `app.webb.tools`. We can then open a subsequent PR with create2 addresses to continue with that work. 

@salman01zp can you please ensure we have at least 1 hosted relayer to support the deployments on `main`.

**Comment by salman01zp** [comment]
Right now proposals are not signed by DKG so we cannot use it with relayer. There is one option we can have one relayer with mocked_backend

**Comment by AtelyPham** [comment]
Yeah, I think it's good to have the dapp works with the relayer on live testnets right now. Then, we can integrate with the `dkg` later once all the components are ready.

**Comment by dutterbutter** [comment]
@salman01zp yes having one relayer with a mocked backend makes sense for the `main` deployments.

**Comment by salman01zp** [comment]
@AtelyPham You can use [this](https://www.notion.so/hicommonwealth/Bridge-Testnet-Deployments-846bbf7802154d97bad79ea745f458a1?pvs=4#bb2a80226f0f4edb901d5c00e3eb9c92) contract addresses for testing using mocked backend.

Relayer : https://relayer1.webb.tools/api/v1/info

**Comment by dutterbutter** [comment]
@AtelyPham please resolve conflicts when you can

**Comment by dutterbutter** [comment]
@devpavan04 and I will QA this for each flow so please do not merge this until we've both approved.

**Comment by devpavan04** [comment]
**Withdrawal from Mumbai fails**

**Error**:

Screenshot 2023-02-16 at 11 42 35 AM

**Video**:

https://user-images.githubusercontent.com/53374218/219470475-7a6d5005-8e48-47b0-87a3-74e3c51e68c5.mov

**Comment by AtelyPham** [comment]
NOTE: When you make a deposit, please wait for a few minutes (2-3 minutes) to make sure the relayer sync blocks and relay roots, then you can withdraw or transfer.

cc: @dutterbutter @devpavan04.

**Comment by AtelyPham** [comment]
> **Withdrawal from Mumbai fails**
> 
> **Error**:
> 
> Screenshot 2023-02-16 at 11 42 35 AM
> 
> **Video**:

Try to clear your localStorage before making a deposit.

**Comment by dutterbutter** [comment]
Still getting a failed withdraw with Goerli to Optimism. Error remains `Error: fetched leaves do not match bridged anchor state`. I did wait some time before attempting to withdraw. I will re-try the transaction a bit later and follow up here.  

 
CleanShot 2023-02-17 at 07 29 18

**Comment by dutterbutter** [comment]
Switching chains to Moonbase Alpha results in the following error. Looks like the value provided for the token symbol does not match what MetaMask is expecting. Another reason why we should be fetching token symbol names on-chain. 

```
MetaMask - RPC Error: nativeCurrency.symbol does not match currency symbol for a network the user already has added with the same chainId. Received:
MDEV 
{code: -32602, message: 'nativeCurrency.symbol does not match currency symb…y has added with the same chainId. Received:\nMDEV'}
code
: 
-32602
message
: 
"nativeCurrency.symbol does not match currency symbol for a network the user already has added with the same chainId. Received:\nMDEV"
[[Prototype]]
: 
Object
```

**Comment by dutterbutter** [comment]
Attempting to withdraw very small amounts (e.g. 0.0005) results in a crash. 

tinpr4

**Comment by dutterbutter** [comment]
Please remove Arbitrum from Source chain list as we are not supporting the network at this time. 

CleanShot 2023-02-17 at 07 57 49

**Comment by AtelyPham** [comment]
> Please remove Arbitrum from Source chain list as we are not supporting the network at this time.
> 
> CleanShot 2023-02-17 at 07 57 49

The Arbitrum is removed in PR https://github.com/webb-tools/webb-dapp/pull/1011

**Comment by dutterbutter** [comment]
Text overflow on Confirm transfer component:

CleanShot 2023-02-17 at 08 07 53

**Comment by devpavan04** [comment]
@dutterbutter @AtelyPham @monaiuu 

Do we need to show connected label in select `destination chain` component. It needs to be shown as the user might want to select a different chain. But, showing the label in `destination chain` seems like a non selectable chain at first intuitively 
 from a user perspective. 
 
 
Screenshot 2023-02-17 at 8 07 21 AM

**Comment by devpavan04** [comment]
Deposited asset's balance is shown in `withdraw` component but not shown in `transfer` component.


https://user-images.githubusercontent.com/53374218/219710003-d289e13f-612a-46a2-ac49-66c38dc17ee7.mov

**Comment by AtelyPham** [comment]
> Deposited asset's balance is shown in `withdraw` component but not shown in `transfer` component.

For transfers, you have to select a destination chain to show the balance.

**Comment by dutterbutter** [comment]
Withdraws are now working for me and transfers work when a relayer is NOT used.

**Comment by devpavan04** [comment]
1. I'm connected to `optimism`
2. I have a deposited `webbETH` balance
3. I switch to `transfer` tab, I select the destination chain to make a transfer (It shows only `optimism`)

If we are showing only the chain on which the deposited asset is on (In this case `webbETH` and `optimism`) why do we need `destination` chain selection component? In this case I think we should pre populate the destination chain input field with the only one option (In this case `optimism`). Is this the intended behaviour or are we supposed to show other chains too?


https://user-images.githubusercontent.com/53374218/219767921-a7afb409-e41b-43bd-af84-f3bcb0fa0625.mov

**Comment by devpavan04** [comment]
Withdraws and transfers(with NO relayer) are working for me too.

**Comment by dutterbutter** [comment]
> 1. I'm connected to `optimism`
> 2. I have a deposited `webbETH` balance
> 3. I switch to `transfer` tab, I select the destination chain to make a transfer (It shows only `optimism`)
> 
> If we are showing only the chain on which the deposited asset is on (In this case `webbETH` and `optimism`) why do we need `destination` chain selection component? In this case I think we should pre populate the destination chain input field with the only one option (In this case `optimism`). Is this the intended behaviour or are we supposed to show other chains too?

This can be addressed in a task improvement. @devpavan04 can you post an issue for it please.

**Review by dutterbutter — APPROVED** [review]

**Comment by AtelyPham** [comment]
@devpavan04 Please review this PR whenever you have a chance, once you approve it, we can merge and ship it to production.

**Comment by devpavan04** [comment]
Error after connecting to the wallet.
Screenshot 2023-02-20 at 9 41 29 AM
Screenshot 2023-02-20 at 9 41 54 AM

**Comment by devpavan04** [comment]
Same issue 👆🏻 Unable to switch to `transfer` and `withdraw` tab. Cleared local storage too.

**Comment by AtelyPham** [comment]
Some updates from the relayers that make the capabilities `undefined`, added checks for it. @devpavan04 Please review it again.

**Comment by devpavan04** [comment]
@AtelyPham Transfer is failing with the error: `Invalid Relayer Address`. Why do we still show `relayer` address in `transfer confirmation` card even after removing `relayer` input field from `transfer`?

Screenshot 2023-02-20 at 11 04 28 AM
Screenshot 2023-02-20 at 11 04 39 AM

**Comment by AtelyPham** [comment]
A good catch here! My bad, because when you select the relayer in the withdraw tab, the active relayer still has the value, so when you switch to the transfer tab, the relayer still has value. Let me update 🙏.

**Comment by devpavan04** [comment]
@AtelyPham Transfer is failing with `Internal JSON-RPC error` : `Insufficient Balance`. Actual webbETH balance: `0.001`.

Screenshot 2023-02-20 at 11 28 18 AM

**Comment by AtelyPham** [comment]
Your input note is already spent @devpavan04.

**Comment by devpavan04** [comment]
@AtelyPham But it still shows up in the table and balance.
Screenshot 2023-02-20 at 11 33 51 AM
Screenshot 2023-02-20 at 11 34 06 AM

**Comment by AtelyPham** [comment]
Switch to Moonbase Alpha, then you can try to delete that note and click the sync notes button to get the available notes on-chain. @devpavan04

**Comment by devpavan04** [comment]
`change amount` is not shown in `withdraw confirmation` component.
Balance: `0.002`
Withdraw amount: `0.001`
Remainder shown in `withdraw`: `0.001`
Change amount shown in `withdraw confirmation`: `0`

Screenshot 2023-02-21 at 5 09 58 AM
Screenshot 2023-02-21 at 5 10 16 AM

**Comment by devpavan04** [comment]
`withdraw` fails on `sepolia`. I made sure to `sync notes` before withdrawing from sepolia.
Balance: `0.004`
Withdraw amount: `0.001`
Remainder shown in withdraw: `0.003`
Change amount shown in withdraw confirmation: 0

Error: `execution reverted: Input is already spent`

Screenshot 2023-02-21 at 5 18 22 AM
Screenshot 2023-02-21 at 5 19 28 AM

**Comment by devpavan04** [comment]
I withdrew `0.101 WEBBETH` to this wallet 👇🏻 on `Optimism`. But the balance is not shown.
Screenshot 2023-02-21 at 5 29 44 AM
Screenshot 2023-02-21 at 5 29 54 AM

**Comment by devpavan04** [comment]
`withdraw` fails on `moonbase alpha`. I made sure to `sync notes` before withdrawing from moonbase alpha.
Balance: `0.005`
Withdraw amount: `0.001`
Remainder shown in withdraw: `0.004`
Change amount shown in withdraw confirmation: 0

Error: `VM Exception while processing transaction: revert Input is already spent`

Screenshot 2023-02-21 at 5 35 50 AM
Screenshot 2023-02-21 at 5 37 43 AM
Screenshot 2023-02-21 at 5 35 41 AM

**Comment by devpavan04** [comment]
`transfer` fails on `sepolia`. I made sure to `sync notes` before transferring from sepolia.
Balance: `0.005`
Withdraw amount: `0.000001`

Error: `Input is already spent`

Screenshot 2023-02-21 at 5 47 42 AM
Screenshot 2023-02-21 at 5 47 59 AM
Screenshot 2023-02-21 at 5 48 15 AM

**Comment by AtelyPham** [comment]
@devpavan04 For the remainder value and change amount.

`remainder` = `total balance` - `amount`
`change amount` = `sum of all input notes` - `amount`

Make sure you clear your notes before clicking the sync notes button.

**Comment by devpavan04** [comment]
> 

Oh that's right Tin. Got confused between `change amount` and `remainder amount`. We need to be clear about this in the documentation. It is easy for a user to get confused.

**Comment by AtelyPham** [comment]
> 
> Oh that's right Tin. Got confused between `change amount` and `remainder amount`. We need to be clear about this in the documentation. It is easy for a user to get confused.

I agree with you about this 👍.

**Comment by devpavan04** [comment]
@AtelyPham @dutterbutter Noticed this behaviour:

- Transferred asset from `sepolia` to different account on `sepolia`.
- The different account is connected to `optimism`.
- To see the asset received from `sepolia` I synced notes while still connected to `optimism` -> Newly received notes was not reflected in the notes table.
- I switched to `sepolia` and then synced notes -> I was able to see newly  received notes in the notes table.

Is this the intended behaviour?

**Comment by AtelyPham** [comment]
> @AtelyPham @dutterbutter Noticed this behaviour:
> 
> * Transferred asset from `sepolia` to different account on `sepolia`.
> * The different account is connected to `optimism`.
> * To see the asset received from `sepolia` I synced notes while still connected to `optimism` -> Newly received notes was not reflected in the notes table.
> * I switched to `sepolia` and then synced notes -> I was able to see newly  received notes in the notes table.
> 
> Is this the intended behaviour?

Yes, FYI, the fetched notes are the notes where each note has the source chain is equal to the active chain.

**Comment by devpavan04** [comment]
> 

Got it Tin! Thanks. We also need to include this in the docs.

**Comment by devpavan04** [comment]
@AtelyPham

Transfer failed on `optimism`. Error: `Invalid relayer address`. We are not using a relayer for transfers right?

**Comment by drewstone** [comment]
Relayer is used for everything except deposits.

**Pull request merged**
