### PR TITLE
Account Stats Tables UI

### PR DESCRIPTION
**Pull request by AtelyPham**
## Summary of changes
- Add empty account stats tables
- Add UI for shielded assets table
- Add UI for spend notes table
- Fix the `DefaultTokenIcon` render error when providing not existing token symbol
- Add new icons for the `Manage` button on the account stats table
- Allowing unstyled `Tab`/`Tabs` components
- Allowing custom shorten function on the `KeyValueWithButton` component

### Reference issue to close (if applicable)
- Closes `NaN`

-----
### Code Checklist 

- [x] Tested
- [x] Documented

### Screenshots

**Empty State**

CleanShot 2022-11-08 at 20 44 42@2x
CleanShot 2022-11-08 at 20 44 17@2x

**Has values**

CleanShot 2022-11-08 at 20 42 43@2x
CleanShot 2022-11-08 at 20 42 17@2x

### CODE REVIEW

**Comment by AtelyPham** [comment]
This PR checkout from PR https://github.com/webb-tools/webb-dapp/pull/678. Please review that PR first, then comback and review this PR. Thank you.

**Comment by dutterbutter** [comment]
Couple small UI changes:

This should have the Optimism icon logo not the Ethereum one: 

Screen Shot 2022-11-08 at 8 15 24 AM


This much white space looks odd, we should look to change this. What do you think?

Screen Shot 2022-11-08 at 8 15 35 AM

**Comment by AtelyPham** [comment]
> Couple small UI changes:
> 
> This should have the Optimism icon logo not the Ethereum one:

For the chain icon, we are rendering based on the native token symbol of the currently selected chain. I will update that if it is possible.

> This much white space looks odd, we should look to change this. What do you think?

The design team wants the size of cards and other components (e.g. Token List Card, Chain List Card, ...) to be the same so that we have to have that space for size consistency. But I think the space looks odd too 😄

**Review by dutterbutter — CHANGES_REQUESTED** [review]
Please update the Webb logo here `libs/icons/src/chains/tangle.svg` to reflect the latest. The one contained in this PR has the wrong orientation. @AtelyPham

**Review by AhmedKorim — CHANGES_REQUESTED** [review]

**Pull request merged**
